# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0002_auto_20171123_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='group_name',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='loan_app.Group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equip_name',
            field=models.CharField(max_length=256),
        ),
    ]
