# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0003_auto_20171123_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='equip_name',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='loan_app.Equipment'),
            preserve_default=False,
        ),
    ]
