# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0004_loan_equip_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='return_date',
            field=models.DateField(default='9999-01-01'),
        ),
    ]
