# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0005_auto_20171123_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='return_or_not',
            field=models.BooleanField(default=False),
        ),
    ]
