# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0006_loan_return_or_not'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='return_or_not',
        ),
        migrations.AddField(
            model_name='loan',
            name='return_code',
            field=models.BooleanField(default=True),
        ),
    ]
