# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0007_auto_20171123_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='notation',
        ),
        migrations.AddField(
            model_name='loan',
            name='notation',
            field=models.TextField(default=1, max_length=512),
            preserve_default=False,
        ),
    ]
