# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0008_auto_20171123_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='equip_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='loan_app.Equipment'),
        ),
    ]
