# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 09:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0009_auto_20171123_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=256)),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_app.Group')),
            ],
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='group_name',
        ),
        migrations.AlterField(
            model_name='loan',
            name='equip_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_app.Equipment', verbose_name='設備名稱'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(auto_now_add=True, verbose_name='歸還日期'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='notation',
            field=models.TextField(blank=True, max_length=512, verbose_name='註記'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='數量'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='type_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loan_app.Type'),
            preserve_default=False,
        ),
    ]
