# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0010_auto_20171124_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='equip_name',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='type_name',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='equip_name',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='quantity',
        ),
        migrations.AddField(
            model_name='equipment',
            name='group_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loan_app.Group', verbose_name='設備'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='item_no',
            field=models.PositiveIntegerField(default=1, verbose_name='物品序號'),
        ),
        migrations.AddField(
            model_name='group',
            name='location',
            field=models.CharField(default=11, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='notation',
            field=models.TextField(blank=True, max_length=512, verbose_name='備註'),
        ),
        migrations.AddField(
            model_name='group',
            name='unit',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='yaer',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='group_name',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='loan_app.Group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='notation',
            field=models.TextField(blank=True, max_length=512, verbose_name='備註'),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
