# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0011_auto_20171127_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='notation',
        ),
        migrations.AddField(
            model_name='equipment',
            name='notation',
            field=models.TextField(blank=True, max_length=512, verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=256, verbose_name='物品名稱'),
        ),
        migrations.AlterField(
            model_name='group',
            name='location',
            field=models.CharField(max_length=256, verbose_name='使用地點'),
        ),
        migrations.AlterField(
            model_name='group',
            name='unit',
            field=models.CharField(max_length=256, verbose_name='使用單位'),
        ),
        migrations.AlterField(
            model_name='group',
            name='yaer',
            field=models.CharField(max_length=256, verbose_name='採購年度'),
        ),
    ]
